name: NodeJS with Webpack

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}    
      run: |
        npm install
        npm run build        
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git config --global user.email "roberto.previtera@gmail.com"
        git config --global user.name "previ"
        npm run deploy

